---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "todo-app-consumer.name" . }}-secret
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "todo-app-consumer.name" .}}
# data:
#   DB_USER: {{ .Values.data.DB_USER }}
#   DB_PASSWORD: {{ .Values.data.DB_PASSWORD }}