data:
  elastic_endpoint: ""
  kafka_broker: ""
  kafka_topic: "todotask"

replicaCount: 3

progressDeadlineSecondsCount: 120

minReadySecondsCount: 30

namespace: ""

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0

imagePullSecrets: ""

image:
  name: todo
  repository: ""
  pullPolicy: Always


appContainer:
  containerPort: 3000


requests:
  memory: "100Mi"
  cpu: "500m"
limits:
  memory: "256Mi"
  cpu: "1000m"
